---
title: "lecture 3"
format: pdf
editor: visual
toc: true
number-sections: true
---

# LUXEMBURG DATA PROJECT

```{r packages }
library(dplyr)
library(purrr)
library(readxl)
library(stringr)
library(janitor)

```

## Getting Data

```{r}
#the link for the data

url      <- "https://is.gd/1vvBAc"
raw_data <- tempfile(fileext = ".xslx")
download.file(url , raw_data , method = "auto" , mode = "wb")

sheets <- excel_sheets(raw_data)

```

```{r}

read_clean <- function(..., sheet){

  read_excel(..., sheet = sheet) |>

    mutate(year = sheet)

}

raw_data <- map(
  sheets,
  ~read_clean(raw_data,
              skip = 10,
              sheet = .)
) |>
  bind_rows() |> 
  clean_names()

raw_data
```

Some variables has their original names and we will change them to English

```{r}
raw_data <- raw_data |>

  rename(

    locality = commune,

    n_offers = nombre_doffres,

    average_price_nominal_euros = prix_moyen_annonce_en_courant,

    average_price_m2_nominal_euros = prix_moyen_annonce_au_m2_en_courant,

    average_price_m2_nominal_euros = prix_moyen_annonce_au_m2_en_courant

  ) |>

  mutate(locality = str_trim(locality)) |>

  select(year, locality, n_offers, starts_with("average"))

raw_data
```

let's find some typos

```{r}
raw_data |> 
  filter(grepl("Luxembourg" , locality)) |>  
  count(locality)
```

```{r}
raw_data |> filter(grepl("P.tange" , locality)) |> 
  count(locality)
```
